package pl.zimowski.karty;

public enum PocketHand169Enum {
    PocketAA("Pocket Rockets"),
    PocketKK("Cowboys"),
    PocketQQ("Ladies"),
    PocketJJ("Fish hooks"),
    PocketTT("Rin Tin Tin"),
    Pocket99("Gretzky"),
    Pocket88("Snowmen"),
    Pocket77("Hockey Sticks"),
    Pocket66("Route 66"),
    Pocket55("Speed Limit"),
    Pocket44("Sailboats"),
    Pocket33("Crabs"),
    Pocket22("Ducks"),
    PocketAKs("Big Slick, suited"),
    PocketAKo("Big Slick, offsuit"),
    PocketAQs("Little Slick"),
    PocketAQo("Little Slick"),
    PocketAJs("Blackjack, suited"),
    PocketAJo("Blackjack, offsuit"),
    PocketATs("A-Team, suited"),
    PocketATo("A-Team, offsuit"),
    PocketA9s("Ace/Nine suited"),
    PocketA9o("Ace/Nine offsuit"),
    PocketA8s("Dead Man's Hand, suited"),
    PocketA8o("Dead Man's Hand, offsuit"),
    PocketA7s("Ace/seven suited"),
    PocketA7o("Ace/seven offsuit"),
    PocketA6s("Ace/Six suited"),
    PocketA6o("Ace/Six offsuit"),
    PocketA5s("Ace/Five suited"),
    PocketA5o("Ace/Five offsuit"),
    PocketA4s("Ace/Four suited"),
    PocketA4o("Ace/Four offsuit"),
    PocketA3s("Friday The 13th, suited"),
    PocketA3o("Friday The 13th, offsuit"),
    PocketA2s("Drinking Age, suited"),
    PocketA2o("Drinking Age, offsuit"),
    PocketKQs("Royal Marriage"),
    PocketKQo("Mixed Marriage"),
    PocketKJs("Kojak"),
    PocketKJo("Bachelor Hand"),
    PocketKTs("King/Ten suited"),
    PocketKTo("King/Ten offsuit"),
    PocketK9s("Canine, suited"),
    PocketK9o("Canine, offsuit"),
    PocketK8s("King/Eight suited"),
    PocketK8o("King/Eight offsuit"),
    PocketK7s("King Salmon, suited"),
    PocketK7o("King Salmon, offsuit"),
    PocketK6s("King/Six suited"),
    PocketK6o("King/Six offsuit"),
    PocketK5s("King/Five suited"),
    PocketK5o("King/Five offsuit"),
    PocketK4s("King/Four suited"),
    PocketK4o("King/Four offsuit"),
    PocketK3s("King Crab, suited"),
    PocketK3o("King Crab, offsuit"),
    PocketK2s("King/Two suited"),
    PocketK2o("King/Two offsuit"),
    PocketQJs("Maverick, suited"),
    PocketQJo("Maverick, offsuit"),
    PocketQTs("Q-Tip, suited"),
    PocketQTo("Q-Tip, offsuit"),
    PocketQ9s("Queen/Nine suited"),
    PocketQ9o("Queen/Nine offsuit"),
    PocketQ8s("Queen/Eight suited"),
    PocketQ8o("Queen/Eight offsuit"),
    PocketQ7s("Computer Hand, suited"),
    PocketQ7o("Computer Hand, offsuit"),
    PocketQ6s("Queen/Six suited"),
    PocketQ6o("Queen/Six offsuit"),
    PocketQ5s("Queen/Five suited"),
    PocketQ5o("Queen/Five offsuit"),
    PocketQ4s("Queen/Four suited"),
    PocketQ4o("Queen/Four offsuit"),
    PocketQ3s("Posh Gay Waiter"),
    PocketQ3o("San Francisco Busboy"),
    PocketQ2s("Queen/Two suited"),
    PocketQ2o("Queen/Two offsuit"),
    PocketJTs("Cloutier, suited"),
    PocketJTo("Cloutier, offsuit"),
    PocketJ9s("Jack/Nine suited"),
    PocketJ9o("Jack/Nine offsuit"),
    PocketJ8s("Jack/Eight suited"),
    PocketJ8o("Jack/Eight offsuit"),
    PocketJ7s("Jack Daniel's, suited"),
    PocketJ7o("Jack Daniel's, offsuit"),
    PocketJ6s("Railroad Hand, suited"),
    PocketJ6o("Railroad Hand, offsuit"),
    PocketJ5s("Jackson Five, suited"),
    PocketJ5o("Jackson Five, offsuit"),
    PocketJ4s("Flat Tire, suited"),
    PocketJ4o("Flat Tire, offsuit"),
    PocketJ3s("Jack/Three suited"),
    PocketJ3o("Jack/Three offsuit"),
    PocketJ2s("Jack/Two suited"),
    PocketJ2o("Jack/Two offsuit"),
    PocketT9s("Ten/Nine suited"),
    PocketT9o("Ten/Nine offsuit"),
    PocketT8s("Ten/Eigth suited"),
    PocketT8o("Ten/Eight offsuit"),
    PocketT7s("Ten/Seven suited"),
    PocketT7o("Ten/Seven offsuit"),
    PocketT6s("Ten/Six suited"),
    PocketT6o("Ten/Six offsuit"),
    PocketT5s("Five and Dime, suited"),
    PocketT5o("Five and Dime, offsuit"),
    PocketT4s("Good Buddy, suited"),
    PocketT4o("Good Buddy, offsuit"),
    PocketT3s("Ten/Three suited"),
    PocketT3o("Ten/Three offsuit"),
    PocketT2s("Texas Dolly, suited"),
    PocketT2o("Texas Dolly, offsuit"),
    Pocket98s("Oldsmobile, suited"),
    Pocket98o("Oldsmobile, offsuit"),
    Pocket97s("Nine/Seven suited"),
    Pocket97o("Nine/Seven offsuit"),
    Pocket96s("Prom Night"),
    Pocket96o("Big Lick"),
    Pocket95s("Full-Time Job, suited"),
    Pocket95o("Full-Time Job, offsuit"),
    Pocket94s("Gold Rush, suited"),
    Pocket94o("Gold Rush, offsuit"),
    Pocket93s("The Sik, suited"),
    Pocket93o("The Sik, offsuit"),
    Pocket92s("Montana Banana, suited"),
    Pocket92o("Montana Banana, offsuit"),
    Pocket87s("Eight/Seven Suited"),
    Pocket87o("Eight/Seven offsuit"),
    Pocket86s("Maxwell Smart, suited"),
    Pocket86o("Maxwell Smart, offsuit"),
    Pocket85s("Eight/Five suited"),
    Pocket85o("Eight/Five offsuit"),
    Pocket84s("Eight/Four suited"),
    Pocket84o("Eight/Four offsuit"),
    Pocket83s("Raquel Welch, suited"),
    Pocket83o("Raquel Welch, offsuit"),
    Pocket82s("Eight/Two suited"),
    Pocket82o("Eight/Two offsuit"),
    Pocket76s("Philadelphia, suited"),
    Pocket76o("Philadelphia, offsuit"),
    Pocket75s("Ketchup, suited"),
    Pocket75o("Ketchup, offsuit"),
    Pocket74s("Double Down, suited"),
    Pocket74o("Double Down, offsuit"),
    Pocket73s("Seven/Three suited"),
    Pocket73o("Seven/Three offsuit"),
    Pocket72s("Velvet Hammer"),
    Pocket72o("Beer Hand"),
    Pocket65s("Six/Five suited"),
    Pocket65o("Six/Five offsuit"),
    Pocket64s("Six/Four suited"),
    Pocket64o("Six/Four offsuit"),
    Pocket63s("Blocky, suited"),
    Pocket63o("Blocky, offsuit"),
    Pocket62s("Ainsworth, suited"),
    Pocket62o("Ainsworth, offsuit"),
    Pocket54s("Five/Four suited"),
    Pocket54o("Five/Four offsuit"),
    Pocket53s("Five/Three suited"),
    Pocket53o("Five/Three offsuit"),
    Pocket52s("Bomber, suited"),
    Pocket52o("Bomber, offsuit"),
    Pocket43s("Four/Three suited"),
    Pocket43o("Four/Three offsuit"),
    Pocket42s("Willie Mays, suited"),
    Pocket42o("Willie Mays, offsuit"),
    Pocket32s("Can of Corn, suited"),
    Pocket32o("Can of Corn, offsuit"),
    None(-1);  /* Not a PocketPairType */

    // ------------------- definition -------------------
    private int _val = -2;
    private String _name;
    private PocketHand169Enum() {}
    private PocketHand169Enum(int aVal) { _val = aVal; }
    private PocketHand169Enum(String aName) { _name = aName; }
    public int getValue() { return _val==-2?ordinal():_val; }
    public String getName() { return _name==null?"":_name; }
}
